// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.LoadbalancerBackendLatency.Record(context.Background(), 1)
	tb.LoadbalancerBackendOutcome.Add(context.Background(), 1)
	tb.LoadbalancerBackendSendFailedLogRecords.Add(context.Background(), 1)
	tb.LoadbalancerBackendSendFailedMetricPoints.Add(context.Background(), 1)
	tb.LoadbalancerBackendSendFailedSpans.Add(context.Background(), 1)
	tb.LoadbalancerBackendSentLogRecords.Add(context.Background(), 1)
	tb.LoadbalancerBackendSentMetricPoints.Add(context.Background(), 1)
	tb.LoadbalancerBackendSentSpans.Add(context.Background(), 1)
	tb.LoadbalancerNumBackendUpdates.Add(context.Background(), 1)
	tb.LoadbalancerNumBackends.Record(context.Background(), 1)
	tb.LoadbalancerNumResolutions.Add(context.Background(), 1)
	AssertEqualLoadbalancerBackendLatency(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendOutcome(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSendFailedLogRecords(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSendFailedMetricPoints(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSendFailedSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSentLogRecords(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSentMetricPoints(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerBackendSentSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumBackendUpdates(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumBackends(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualLoadbalancerNumResolutions(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
